---
- name: Create Nginx server
  hosts: web
  vars:
    worker_root: /home/ansible-worker/www/stud-template
    nginx_config: ansible.iphilka.ru.conf
    nginx_available: /etc/nginx/sites-available
    nginx_enabled: /etc/nginx/sites-enabled
  become: true
  tasks:
    - name: Create ansible-worker user
      user:
        name: ansible-worker
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Copy SSH keys
      copy:
        src: ssh_keys/
        dest: ~/.ssh/
        mode: 0600

    - name: Clone repository
      git:
        repo: "https://github.com/iphilka/stud-template.git"
        dest: "{{ worker_root }}"
        force: yes
      become_user: ansible-worker

    - name: Rewrite index.html
      copy:
        src: index.html
        dest: "{{ worker_root }}"

    - name: Remove nginx
      apt:
        name: nginx
        state: absent 

    - name: Install nginx
      apt:
        name: nginx
        state: present 

    - name: Add nginx configuration
      copy:
        dest: "{{ nginx_available }}"
        src: "{{ nginx_config }}"
        owner: root
        group: root
        mode: 0755
      notify: Reload nginx

    - name: Enable site
      become: yes
      file:
        src: "{{ nginx_available }}/{{ nginx_config }}"
        dest: "{{ nginx_enabled }}/{{ nginx_config  }}"
        state: link
        force: yes

    - name: Remove default config
      become: yes
      file:
        path: "{{ nginx_enabled }}/default"
        state: absent

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: restarted
