---
- name: Create Nginx server
  hosts: web
  vars:
    worker_root: /home/ansible-worker/www/stud-template
  become: true
  tasks:
    - name: Create ansible-worker user
      user:
        name: ansible-worker
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Copy SSH keys
      copy:
        src: ssh_keys/
        dest: ~/.ssh/
        mode: 0600

    - name: Clone repository
      git:
        repo: "https://github.com/iphilka/stud-template.git"
        dest: "{{ worker_root }}"
      become_user: ansible-worker

    - name: Rewrite index.html
      copy:
        src: index.html
        dest: "{{ worker_root }}"

    - name: Add Nginx configuration
      copy:
        dest: "/etc/nginx/sites-available/ansible.iphilka.ru.conf"
        src: ansible.iphilka.ru.conf
      notify: Reload nginx

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded



